name: Build-golang

on: 
    push:
        paths-ignore:
            - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      uses: Mushus/golangci-linter@v1
        
    - name: Build
      run: go build -v .
      
    # I'll enable this when tests are actually written
    #- name: Test
      #run: go test -v .
  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tetrafour_linux
        path: tetrafour*

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  uploadDocker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [build]
    # disabled for testing
    #if: github.ref == 'refs/heads/develop'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build --tag tetrafour .

      - name: ECR upload
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: tetrafour
          image: tetrafour:dev-${{ github.sha }}
